# Generated by Django 5.2.16 on 2026-07-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Usermname',
            new_name='Username',
        ),
    ]
