# Generated by Django 5.2.16 on 2026-07-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_rename_usermname_owner_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Username',
            new_name='username',
        ),
    ]
