# Generated by Django 5.2.16 on 2026-07-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
