# Generated by Django 5.2.16 on 2026-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_alter_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200, unique=True)),
                ('rack_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
