# Generated by Django 5.2.16 on 2026-08-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_customer_feedback_order_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('asap', 'As Soon As Possible'), ('scheduled', 'Scheduled')], default='asap', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
