# Generated by Django 5.2.16 on 2026-08-13 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_delivery_area_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='owner.delivery_area'),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='owner.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_items', to='owner.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'product'), name='unique_customer_product_wishlist')],
            },
        ),
    ]
